spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cndb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whale.lms.pojo
  configuration:
    map-underscore-to-camel-case: true
